[package]
name = "embedder"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
example = "1.1.0"
serde_json = "1.0.117"
tokio = { version = "1", features = ["full"] }
wasi = "0.13.1"
wasi-common = "21.0.1"
wasmtime-wasi = "21.0.1"
wasmtime = "21.0.1"
